# values.yaml for kube-prometheus-stack

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-credentials
  service:
    type: NodePort
    port: 80
    targetPort: 3000
  ingress:
    enabled: false
  persistence:
    enabled: true
    size: 5Gi
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true

# Add tolerations so Prometheus & Grafana pods can be scheduled on master nodes if needed
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
